on:
  push:
  pull_request:
    branches:
      - devel
  schedule:
    - cron: '0 9 * * 5'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.image }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc }} - ${{ matrix.config.image }} - ${{ matrix.config.pandoc }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, bioc: 'devel'}
        - { os: macOS-latest, bioc: 'devel', curlConfigPath: '/usr/bin/'}
        - { os: macOS-latest, bioc: 'devel', pandoc: '2.11.4', curlConfigPath: '/usr/bin/'}
#        - { os: ubuntu-latest, bioc: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
        - { os: ubuntu-latest, bioc: 'devel'}
        - { os: ubuntu-latest, image: 'bioconductor/bioconductor_docker:devel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CURL_CONFIG: ${{ matrix.config.curlConfigPath }}curl-config

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        if: matrix.config.image == null
        with:
          bioc-version: ${{ matrix.config.bioc }}

      - name: Set up pandoc (default version)
        uses: r-lib/actions/setup-pandoc@v2
        if: matrix.config.image == null && matrix.config.pandoc == null

      - name: Set up pandoc (specified version)
        uses: r-lib/actions/setup-pandoc@v2
        if: matrix.config.image == null && matrix.config.pandoc != null
        with:
          pandoc-version: ${{ matrix.config.pandoc }}

      - name: Set bitmapType
        if: runner.os == 'macOS'
        run: echo 'options(bitmapType = "cairo")' >> $HOME/.Rprofile

      - name: Install remotes and rmarkdown
        run: |
          install.packages(c('remotes', 'rmarkdown'))
        shell: Rscript {0}

      - name: Test pandoc configuration
        run: |
          rmarkdown::pandoc_available()
          rmarkdown::pandoc_version()
          rmarkdown::pandoc_exec()
          rmarkdown::pandoc_citeproc_args()
          file.exists(file.path(dirname(rmarkdown::pandoc_exec()), "pandoc-citeproc"))
          Sys.which("pandoc")
          Sys.which("pandoc-citeproc")
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows' && matrix.config.image == null
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install harfbuzz
          brew install fribidi

      - name: Install dependencies
        run: |
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
          remotes::install_cran('rcmdcheck', Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Upload install log if the build/install/check step fails
        if: always() && (steps.build-install-check.outcome == 'failure')
        uses: actions/upload-artifact@v3
        with:
          name: install-log
          path: |
            ${{ steps.build-install-check.outputs.install-log }}

      - name: Show testthat output (windows)
        if: always() && runner.os == 'Windows'
        run: |
            type ${{ steps.build-install-check.outputs.check-dir }}\tests\testthat.Rout
        shell: cmd

      - name: Show testthat output (non-windows)
        if: always() && runner.os != 'Windows'
        run: |
            cat ${{ steps.build-install-check.outputs.check-dir }}/tests/testthat.Rout
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-results
          path: ${{ steps.build-install-check.outputs.check-dir }}

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          arguments: '--no-check-bioc-views --no-check-bioc-help'
          error-on: 'error'

      - name: Test coverage
        if: matrix.config.os == 'macOS-latest' && matrix.config.pandoc == null
        run: |
          install.packages("covr")
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/devel' && matrix.config.os == 'macOS-latest' && matrix.config.pandoc == null
        run: |
          R CMD INSTALL .
          Rscript -e "remotes::install_dev('pkgdown'); pkgdown::deploy_to_branch(new_process = FALSE)"

